### ISSUE TITLE
hlx up fails with node 15.x

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#566]
creating a copy of the request object fails:
https://github.com/adobe/helix-simulator/blob/e956baec0e458e8d5f2d19abfd05e13d7f189593/src/RequestContext.js#L24

which leads to:

```
TypeError: headers.get is not a function
    at getOriginalHost (/Users/uncled/code/pages/.hlx/pages/master/src/utils.js:28:23)
    at getAbsoluteUrl (/Users/uncled/code/pages/.hlx/pages/master/src/utils.js:47:18)
```

due to: https://github.com/nodejs/node/issues/36550

**Comment by stefan-guggisberg** [comment]
thanks, good to know!
